// <auto-generated />
using Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210822225401_createDatabase")]
    partial class createDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initials")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Weather");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Encoberto com Chuvas Isoladas",
                            Initials = "ec"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Chuvas Isoladas",
                            Initials = "ci"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chuva",
                            Initials = "c"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Instável",
                            Initials = "in"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Possibilidade de Pancadas de Chuva",
                            Initials = "pp"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Chuva pela Manhã",
                            Initials = "em"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Chuva pela Noite",
                            Initials = "en"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Pancadas de Chuva a Tarde",
                            Initials = "pt"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Pancadas de Chuva pela Manhã",
                            Initials = "pm"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Nublado e Pancadas de Chuva",
                            Initials = "np"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Pancadas de Chuva",
                            Initials = "pc"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Parcialmente Nublado",
                            Initials = "pn"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Chuvisco",
                            Initials = "cv"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Chuvoso",
                            Initials = "ch"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Tempestade",
                            Initials = "t"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Predomínio de Sol",
                            Initials = "ps"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Encoberto",
                            Initials = "e"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Nublado",
                            Initials = "n"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Céu Claro",
                            Initials = "cl"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Nevoeiro",
                            Initials = "nv"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Geada",
                            Initials = "g"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Neve",
                            Initials = "ne"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Pancadas de Chuva a Noite",
                            Initials = "pnt"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Possibilidade de Chuva",
                            Initials = "psc"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Possibilidade de Chuva pela Manhã",
                            Initials = "pcm"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Possibilidade de Chuva a Tarde",
                            Initials = "pct"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Possibilidade de Chuva a Noite",
                            Initials = "pcn"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Nublado com Pancadas a Tarde",
                            Initials = "npt"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Nublado com Pacadas a Noite",
                            Initials = "pcn"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Nublado com Possibilidade de Chuva a Noite",
                            Initials = "ncn"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Nublado com Possibilidade de Chuva a Tarde",
                            Initials = "nct"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Nublado com Possibilidade de Chuva pela Manhã",
                            Initials = "ncm"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Nublado com Pancadas pela Manhã",
                            Initials = "npm"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Nublado com Possibilidade de Chuva",
                            Initials = "npp"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Variação de Nebulosidade",
                            Initials = "vn"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Chuva a Tarde",
                            Initials = "ct"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Possibilidade de Pancadas de Chuva a Noite",
                            Initials = "ppn"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Possibilidade de Pancadas de Chuva a Tarde",
                            Initials = "ppt"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Possibilidade de Pancadas de Chuva pela Manhã",
                            Initials = "ppm"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Não Definido",
                            Initials = "lt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
